// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230803131533_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("61d6f3a9-4f1a-4148-8dd2-d82d2372f627"),
                            Address = "Bulgaria",
                            DateOfBirth = new DateTime(1978, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            IBAN = "BG89UNCR70008359568951",
                            Phone = "+359 88 9123456",
                            Surname = "Petrov"
                        },
                        new
                        {
                            PersonId = new Guid("cb0c7e8e-419f-4f18-b482-d19eb5e79408"),
                            Address = "UK",
                            DateOfBirth = new DateTime(1988, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            IBAN = "GB77BARC20037884596399",
                            Phone = "+44 7911 123456",
                            Surname = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
